
sudo: required
language: bash
services: docker

before_install:
# Docker:
- docker build -t ELK-Stack .
- docker images
# HardWare Usage:
- cat /proc/cpuinfo | grep 'model name' | uniq
- cat /proc/cpuinfo | grep processor
- sudo lshw -c memory