sudo: required
language: bash
services: docker


before_install:
# Docker:
- docker build -t elk_image .
- docker images
- docker run -D --name elk_container -p 9300:9300 -p 9200:9200   elk_image
- docker ps -a
# HardWare Usage:
- cat /proc/cpuinfo | grep 'model name' | uniq
- cat /proc/cpuinfo | grep processor
- sudo lshw -c memory
- sudo df -h
# Network Information
- current_ip="$(curl --silent --show-error --fail ipecho.net/plain)"
- echo "Public IP :$current_ip"
# Elastic Search TEST
- curl -XGET 'localhost:9200'