
sudo: required
language: bash
services: docker

env:
- public_ip = $(curl ifconfig.me/ip)

before_install:
# Docker:
- docker build -t elk_stack .
- docker images
# HardWare Usage:
- cat /proc/cpuinfo | grep 'model name' | uniq
- cat /proc/cpuinfo | grep processor
- sudo lshw -c memory
- sudo df -h
# Network Information
- public_ip
- ping public_ip