sudo: required
language: bash
services: docker


before_install:
# Docker:
- docker build -t elk_image .
- docker images
- docker run -d --name elk_container -p 9300:9300 -p 9200:9200   elk_image
- docker ps -a
# HardWare Usage:
- cat /proc/cpuinfo | grep 'model name' | uniq
- cat /proc/cpuinfo | grep processor
- sudo lshw -c memory
- sudo df -h
# Network Information
- current_ip="$(curl --silent --show-error --fail ipecho.net/plain)"
- echo "Public IP :$current_ip"
- ifconfig
# Elastic Search TEST
script:
- docker logs elk_container
- wget -q --waitretry=1 --retry-connrefused -T 10 -O - http://127.0.0.1:9200
- curl --head http://127.0.0.1:9200
- curl --head http://www.yourdomain.com/