sudo: required
language: bash
services: docker

before_install:
- docker pull clarencep/proxy-pool-docker:latest
- docker images
- curl ifconfig.me 
- docker run -d clarencep/proxy-pool-docker:latest
